#ifndef __HEADER_BLOCKTYPE_BI__
#define __HEADER_BLOCKTYPE_BI__

#Define BLOCKTYPE_NUM 7

Enum Blocktype
	BLOCKTYPE_DEFAULT = 0
	BLOCKTYPE_GRASS
	BLOCKTYPE_DIRT
	BLOCKTYPE_WATER
	BLOCKTYPE_STONE
	BLOCKTYPE_WOOD
	BLOCKTYPE_SAND
End Enum

#endif